# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
commands:
  sayit:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "Blablabla"
    steps:
      - run: echo << parameters.to >>

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "hello"
      - run: echo "hello World" > test.txt
      - save_cache:
          key: simpleMesage
          paths:
            - test.txt
      - sayit:
          to: "tobi was here"

  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "world"
      - restore_cache:
          keys:
            - simpleMesages
      - run: echo "printing Text.txt:"
      - run: cat test.txt
      - run: 
          name: error handler
          command: echo "error restoring cache"
          when: on_fail

  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "my name is $TEST_NAME"


workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - print_hello
      - print_world
      - build

  exampleContext:
    jobs:
      - build:
          context: exampleContext